version: 2
updates:

  # Submodules (hosts and some adapters)

  - package-ecosystem: "gitsubmodule"
    directory: "/test/hosts/substrate"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "substrate:"

  - package-ecosystem: "gitsubmodule"
    directory: "/test/hosts/kagome"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "kagome:"
    open-pull-requests-limit: 0

  - package-ecosystem: "gitsubmodule"
    directory: "/test/hosts/gossamer"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gossamer:"

  # Adapters (not handled by submodules)

  - package-ecosystem: "cargo"
    directory: "/test/adapters/substrate"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "substrate-a:"
    open-pull-requests-limit: 0

  - package-ecosystem: "cargo"
    directory: "/test/adapters/substrate-legacy"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "substrate-a-l:"
    open-pull-requests-limit: 0

  # Runtimes (not handled by submodules)

  - package-ecosystem: "cargo"
    directory: "/test/runtimes/hostapi"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "hostapi-rt:"
    open-pull-requests-limit: 0

  - package-ecosystem: "cargo"
    directory: "/test/runtimes/hostapi-legacy"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "hostapi-rt-l:"
    open-pull-requests-limit: 0


  - package-ecosystem: "cargo"
    directory: "/test/runtimes/tester"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "tester-rt:"
    open-pull-requests-limit: 0

  # GitHub Actions

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci:"
